apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ .Values.database.pass }}
  POSTGRES_DB: {{ .Values.database.name }}

  POSTGRES_HOST: {{ .Values.database.host }}
  POSTGRES_PORT: "{{ .Values.database.port }}"
  SERVICE_PORT: "{{ .Values.deployment.port }}"
